name: Continuous Integration

on:
  push:
    branches: [main, dev]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Lua
        uses: MunifTanjim/luver-action@v1

      - name: Install Lua 5.4
        shell: bash
        run: |
          luver install lua 5.4.7
          luver use 5.4.7

      - name: Verify Lua
        shell: bash
        run: |
          lua -v

      - name: Run Tests
        shell: bash
        run: |
          cd tests
          lua run_tests.lua