name: Continuous Integration

on:
  push:
    branches: [main, dev]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC Developer Command Prompt
        uses: step-security/msvc-dev-cmd@v1 

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: "5.4.7"

      - name: Verify Lua
        run: |
          lua -v

      - name: Run Tests
        # Corrected: Explicitly maps the entire path from your root repository layout
        working-directory: ./clinkkit/tests
        run: |
          lua run_tests.lua
